apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: browser-test
resources:
  - statefulset.yaml
  - service.yaml
images:
  - name: registry.edjusted.com/browser-fetch/browser-fetch
    newTag: 20260911-83660f5
